### ISSUE TITLE
Running into gitlab-ci for Autoreporting

### ISSUE THREAD

**Issue by NTHINGs** [git-time-metric/gtm#76]
I am playing around with the project into my Gitlab Pipeline for automating the reports and maybe exporting them. I created a docker image with gtm for running the commands into the pipeline https://hub.docker.com/r/nthingsm/gtm/ and in my .gitlab-ci.yml I have the next stage: 
```yml
time_report:
    stage: time_report
    image: nthingsm/gtm
    script:
        - gtm init
        - git fetchgtm
        - gtm report -this-month -format timeline-hours
```

But the gtm report command doesn't output anything. Am I missing something?

**Comment by NTHINGs** [comment]
FYI managed to get output with this command: 
```yml
time_report:
    stage: time_report
    image: nthingsm/gtm
    script:
        - gtm init
        - git fetchgtm
        - git log --pretty=%H --since="last month" | gtm report -format timeline-hours -this-month
```
